name: On Demand Revalidation
on:
  workflow_dispatch:
    branches: [main]

jobs:
  revalidate:
    name: Revalidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Dependency Package
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.NPMGITHUB_PACKAGE_TOKEN }}
        run: |
          npm install
      - name: Revalidate All Pages
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          npm run app:revalidate
